/**
 * Собирает переносимый .sql из legacy JSON в ./data — удобно для импорта в облако / phpMyAdmin / mysql CLI.
 *
 * Usage:
 *   node src/db/exportJsonToSql.js
 *   node src/db/exportJsonToSql.js --out dumps/app_kv.sql
 *   node src/db/exportJsonToSql.js --data-dir ./data
 */
import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";
import { NS, LEGACY_FILENAME } from "../storage/namespaces.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** Экранирование строкового литерала для одинарных кавычек в MySQL (utf8mb4). */
function escapeSqlString(value) {
  return `'${String(value)
    .replace(/\\/g, "\\\\")
    .replace(/\0/g, "\\0")
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\u001a/g, "\\Z") // CTRL+Z historic
    .replace(/'/g, "\\'")}'`;
}

function parseArgs(argv) {
  let out = path.join(process.cwd(), "exports", "app_kv_from_json.sql");
  let dataDir = path.join(process.cwd(), "data");
  for (let i = 2; i < argv.length; i++) {
    if (argv[i] === "--out" && argv[i + 1]) {
      out = path.resolve(process.cwd(), argv[++i]);
    } else if (argv[i] === "--data-dir" && argv[i + 1]) {
      dataDir = path.resolve(process.cwd(), argv[++i]);
    }
  }
  return { out, dataDir };
}

async function readJsonFromFile(absPath) {
  try {
    const raw = await fs.readFile(absPath, "utf8");
    const o = JSON.parse(raw || "{}");
    return o && typeof o === "object" ? o : {};
  } catch (e) {
    if (e && e.code === "ENOENT") return {};
    throw e;
  }
}

async function loadCreateTableDdl() {
  const mig = path.join(__dirname, "migrations", "001_app_kv.sql");
  const raw = await fs.readFile(mig, "utf8");
  const lines = raw.split(/\r?\n/).filter((ln) => {
    const t = ln.trim();
    return t && !t.startsWith("--");
  });
  return lines.join("\n").trim() + ";";
}

async function main() {
  const { out, dataDir } = parseArgs(process.argv);
  const ddl = await loadCreateTableDdl();

  const parts = [];
  parts.push("-- Generated by src/db/exportJsonToSql.js from ./data/*.json\n");
  parts.push("SET NAMES utf8mb4;\nSET FOREIGN_KEY_CHECKS=0;\n\n");
  parts.push(ddl);
  parts.push("\n\n");

  for (const ns of Object.values(NS)) {
    const fname = LEGACY_FILENAME[ns];
    const abs = path.join(dataDir, fname);
    const obj = await readJsonFromFile(abs);
    const payload = escapeSqlString(JSON.stringify(obj));
    const nsLit = escapeSqlString(ns);
    parts.push(
      `INSERT INTO app_kv (namespace, payload_json) VALUES (${nsLit}, ${payload})\n` +
        "ON DUPLICATE KEY UPDATE payload_json = VALUES(payload_json);\n\n",
    );
  }

  parts.push("SET FOREIGN_KEY_CHECKS=1;\n");

  await fs.mkdir(path.dirname(out), { recursive: true });
  await fs.writeFile(out, parts.join(""), "utf8");
  console.log("[export-json-to-sql] written:", path.relative(process.cwd(), out));
}

main().catch((e) => {
  console.error(e);
  process.exitCode = 1;
});
