import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import { Bot, InlineKeyboard, webhookCallback } from "grammy";
import { Agent } from "undici";
import { config } from "./config.js";
import { validateWebAppInitData } from "./telegramWebApp.js";
import { signSession, verifySession } from "./session.js";
import * as rw from "./remnawave.js";
import * as xuiStore from "./xuiLinksStore.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const publicDir = path.join(__dirname, "..", "public");
const whPath = "/telegram/webhook";

const app = express();
app.use(express.json({ limit: "1mb" }));

if (config.corsOrigin) {
  app.use((req, res, next) => {
    res.setHeader("Access-Control-Allow-Origin", config.corsOrigin);
    res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");
    res.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
    if (req.method === "OPTIONS") return res.sendStatus(204);
    next();
  });
}

function authMiddleware(req, res, next) {
  const h = req.headers.authorization;
  const m = h && /^Bearer (.+)$/.exec(h);
  if (!m) return res.status(401).json({ error: "unauthorized" });
  try {
    req.tgSession = verifySession(m[1]);
    next();
  } catch {
    return res.status(401).json({ error: "bad_token" });
  }
}

app.get("/health", (_req, res) => res.json({ ok: true }));

function isProbablyBase64(s) {
  const t = String(s || "").trim();
  if (!t || t.length < 16) return false;
  if (t.includes("://") || t.includes("\n")) return false;
  return /^[A-Za-z0-9+/=_-]+$/.test(t);
}

function decodeSubscriptionToLines(body) {
  const raw = String(body || "").trim();
  if (!raw) return [];
  let text = raw;
  if (isProbablyBase64(raw)) {
    try {
      text = Buffer.from(raw, "base64").toString("utf8");
    } catch {
      text = raw;
    }
  }
  return text
    .split(/\r?\n/g)
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith("#"));
}

async function fetchText(url, opts = {}) {
  const { insecureTls = false } = opts;
  const controller = new AbortController();
  const t = setTimeout(() => controller.abort(), 10_000);
  try {
    const dispatcher = insecureTls
      ? new Agent({ connect: { rejectUnauthorized: false } })
      : undefined;
    const res = await fetch(url, {
      signal: controller.signal,
      redirect: "follow",
      ...(dispatcher ? { dispatcher } : {}),
    });
    if (!res.ok) {
      const tt = await res.text().catch(() => "");
      throw new Error(`fetch failed: ${res.status} ${tt}`.trim());
    }
    return await res.text();
  } finally {
    clearTimeout(t);
  }
}

function resolveXuiUrlFromLink(link) {
  if (!link) return null;
  if (link.kind === "url") return link.value;
  if (link.kind === "token") {
    if (!config.xui.baseUrl) return null;
    return `${config.xui.baseUrl}/sub/${link.value}`;
  }
  return null;
}

// Public 3X-UI subscription proxy by token (token is generated by the bot on link).
app.get("/sub/xui/:token", async (req, res) => {
  const token = String(req.params.token || "").trim();
  if (!token) return res.status(400).send("token_required");
  try {
    const link = await xuiStore.getXuiLinkByPublicToken(token);
    if (!link) return res.status(404).send("not_found");
    const targetUrl = resolveXuiUrlFromLink(link);
    if (!targetUrl) return res.status(503).send("xui_base_url_required");
    const body = await fetchText(targetUrl, { insecureTls: config.xui.insecureTls });
    res.setHeader("Content-Type", "text/plain; charset=utf-8");
    return res.status(200).send(body);
  } catch (e) {
    return res.status(500).send(String(e?.message || e));
  }
});

// Public merged subscription: Remnawave subscription (by shortUuid) + optional BYPASS_SUBSCRIPTION_URL (e.g. 3X-UI).
app.get("/sub/merged/:shortUuid", async (req, res) => {
  const shortUuid = String(req.params.shortUuid || "").trim();
  if (!shortUuid) return res.status(400).send("short_uuid_required");
  try {
    const user = await rw.getUserByShortUuid(shortUuid);
    if (!user?.subscriptionUrl) return res.status(404).send("subscription_not_found");

    const [rwBody, bypassBody] = await Promise.all([
      fetchText(user.subscriptionUrl),
      config.bypass.subscriptionUrl
        ? fetchText(config.bypass.subscriptionUrl, { insecureTls: config.bypass.insecureTls })
        : Promise.resolve(""),
    ]);

    const lines = new Set([
      ...decodeSubscriptionToLines(rwBody),
      ...decodeSubscriptionToLines(bypassBody),
    ]);

    const out = Array.from(lines).join("\n");
    const b64 = Buffer.from(out, "utf8").toString("base64");
    res.setHeader("Content-Type", "text/plain; charset=utf-8");
    return res.status(200).send(b64);
  } catch (e) {
    return res.status(500).send(String(e?.message || e));
  }
});

app.post("/api/auth/telegram", (req, res) => {
  const { initData } = req.body || {};
  const v = validateWebAppInitData(initData);
  if (!v.ok) return res.status(401).json({ error: v.error });
  const telegramId = v.user.id;
  const token = signSession({
    telegramId,
    username: v.user.username,
  });
  res.json({
    token,
    user: {
      id: telegramId,
      first_name: v.user.first_name,
      username: v.user.username,
    },
  });
});

async function loadMe(telegramId) {
  const base = String(config.publicBaseUrl || "").replace(/\/$/, "");
  const xuiLink = await xuiStore.getXuiLinkByTelegramId(telegramId);
  const xuiPublicUrl =
    base && xuiLink?.publicToken ? `${base}/sub/xui/${xuiLink.publicToken}` : null;

  const users = await rw.getUsersByTelegramId(telegramId);
  const pick = users[0] || null;
  const hasMergeSource = Boolean(config.bypass.subscriptionUrl);
  const mergedUrl =
    base && hasMergeSource && pick?.shortUuid
      ? `${base}/sub/merged/${pick.shortUuid}`
      : null;

  const primary =
    config.subscriptions.primary === "xui" && xuiPublicUrl
      ? xuiPublicUrl
      : mergedUrl || pick?.subscriptionUrl || xuiPublicUrl || null;

  if (!pick) {
    return {
      remnawaveUser: null,
      subscriptionUrl: primary,
      xui: xuiLink ? { linked: true, subscriptionUrl: xuiPublicUrl } : { linked: false },
    };
  }
  return {
    remnawaveUser: {
      uuid: pick.uuid,
      username: pick.username,
      shortUuid: pick.shortUuid,
      status: pick.status,
      expireAt: pick.expireAt,
      subscriptionUrl: primary,
      trafficLimitBytes: pick.trafficLimitBytes,
      hwidDeviceLimit: pick.hwidDeviceLimit ?? null,
      userTraffic: pick.userTraffic || null,
    },
    subscriptionUrl: primary,
    xui: xuiLink ? { linked: true, subscriptionUrl: xuiPublicUrl } : { linked: false },
  };
}

function calcNewDeviceLimit(currentLimit, addSlots) {
  const base = Number.isFinite(Number(currentLimit)) && Number(currentLimit) > 0
    ? Number(currentLimit)
    : config.remnawave.defaultHwidDeviceLimit;
  return Math.max(1, base + Number(addSlots || 0));
}

app.get("/api/me", authMiddleware, async (req, res) => {
  try {
    const tid = Number(req.tgSession.sub || req.tgSession.tg);
    const data = await loadMe(tid);
    res.json(data);
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

app.get("/api/subscription", authMiddleware, async (req, res) => {
  try {
    const tid = Number(req.tgSession.sub || req.tgSession.tg);
    const data = await loadMe(tid);
    res.json(data);
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

app.post("/api/link-subscription", authMiddleware, async (req, res) => {
  const raw = String(req.body?.shortUuid || "").trim();
  if (!raw) return res.status(400).json({ error: "short_uuid_required" });

  // Accept either short UUID itself or full subscription URL.
  const m = raw.match(/\/sub\/([^/?#]+)/i);
  const shortUuid = (m?.[1] || raw).trim();
  if (!shortUuid) return res.status(400).json({ error: "invalid_short_uuid" });

  try {
    const tid = Number(req.tgSession.sub || req.tgSession.tg);
    const alreadyLinked = await rw.getUsersByTelegramId(tid);
    if (alreadyLinked.length) {
      return res.status(409).json({ error: "telegram_already_linked" });
    }

    const user = await rw.getUserByShortUuid(shortUuid);
    if (!user) return res.status(404).json({ error: "subscription_not_found" });

    if (user.telegramId && Number(user.telegramId) !== tid) {
      return res.status(409).json({ error: "subscription_already_linked" });
    }

    await rw.updateUser({
      uuid: user.uuid,
      patch: { telegramId: tid },
    });

    const data = await loadMe(tid);
    return res.json({ ok: true, ...data });
  } catch (e) {
    return res.status(500).json({ error: e.message });
  }
});

// Link 3X-UI subscription to this Telegram user.
// Body: { subscriptionUrlOrToken: "https://.../sub/xxxx" } OR { subscriptionUrlOrToken: "xxxx" }
app.post("/api/link-xui", authMiddleware, async (req, res) => {
  const raw = String(req.body?.subscriptionUrlOrToken || "").trim();
  if (!raw) return res.status(400).json({ error: "subscriptionUrlOrToken_required" });
  try {
    const tid = Number(req.tgSession.sub || req.tgSession.tg);
    await xuiStore.linkXuiSubscription({ telegramId: tid, xuiUrlOrToken: raw });
    const data = await loadMe(tid);
    return res.json({ ok: true, ...data });
  } catch (e) {
    return res.status(500).json({ error: e.message });
  }
});

app.post("/api/unlink-xui", authMiddleware, async (req, res) => {
  try {
    const tid = Number(req.tgSession.sub || req.tgSession.tg);
    await xuiStore.unlinkXuiSubscription({ telegramId: tid });
    const data = await loadMe(tid);
    return res.json({ ok: true, ...data });
  } catch (e) {
    return res.status(500).json({ error: e.message });
  }
});

app.post("/api/webhooks/payment", async (req, res) => {
  if (!config.paymentWebhookSecret) {
    return res.status(503).json({ error: "webhook_disabled" });
  }
  const sec = req.headers["x-webhook-secret"];
  if (sec !== config.paymentWebhookSecret) {
    return res.status(403).json({ error: "forbidden" });
  }
  const { telegramId, extendDays, planDays, addDeviceSlots } = req.body || {};
  const days = Number(extendDays || planDays || 0);
  const slots = Number(addDeviceSlots || 0);
  if (!telegramId || (!Number.isFinite(days) && !Number.isFinite(slots))) {
    return res.status(400).json({ error: "bad_body" });
  }
  if (days < 0 || slots < 0 || (days < 1 && slots < 1)) {
    return res.status(400).json({ error: "nothing_to_apply" });
  }
  try {
    const tid = Number(telegramId);
    let users = await rw.getUsersByTelegramId(tid);
    const squads = config.remnawave.internalSquadUuids;
    if (!users.length) {
      if (days < 1) {
        return res.status(404).json({ error: "subscription_not_found_for_device_addon" });
      }
      const uname = rw.defaultUsernameFromTelegramId(tid);
      const expireAt = rw.addDaysIso(days);
      const created = await rw.createUser({
        username: uname,
        expireAtIso: expireAt,
        telegramId: tid,
        activeInternalSquads: squads,
        hwidDeviceLimit: config.remnawave.defaultHwidDeviceLimit,
      });
      users = [created];
    } else {
      if (days > 0) {
        await rw.bulkExtendExpiration([users[0].uuid], days);
      }
    }
    const patch = {};
    if (squads?.length) {
      patch.activeInternalSquads = squads;
    }
    if (slots > 0) {
      patch.hwidDeviceLimit = calcNewDeviceLimit(users[0]?.hwidDeviceLimit, slots);
    } else if (
      !users[0]?.hwidDeviceLimit &&
      Number(config.remnawave.defaultHwidDeviceLimit) > 0
    ) {
      patch.hwidDeviceLimit = Number(config.remnawave.defaultHwidDeviceLimit);
    }
    if (Object.keys(patch).length) {
      await rw.updateUser({
        uuid: users[0].uuid,
        patch,
      });
    }
    res.json({ ok: true });
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

app.post("/api/test/grant", authMiddleware, async (req, res) => {
  if (!config.testGrantEnabled) {
    return res.status(403).json({ error: "test_grant_disabled" });
  }
  const days = Number(req.body?.days || 30);
  if (!Number.isFinite(days) || days < 1) {
    return res.status(400).json({ error: "bad_days" });
  }
  try {
    const tid = Number(req.tgSession.sub || req.tgSession.tg);
    const users = await rw.getUsersByTelegramId(tid);
    const squads = config.remnawave.internalSquadUuids;
    if (!users.length) {
      const uname = rw.defaultUsernameFromTelegramId(tid);
      const expireAt = rw.addDaysIso(days);
      await rw.createUser({
        username: uname,
        expireAtIso: expireAt,
        telegramId: tid,
        activeInternalSquads: squads,
        hwidDeviceLimit: config.remnawave.defaultHwidDeviceLimit,
      });
    } else {
      await rw.bulkExtendExpiration([users[0].uuid], days);
      const patch = {};
      if (squads?.length) {
        patch.activeInternalSquads = squads;
      }
      if (
        !users[0]?.hwidDeviceLimit &&
        Number(config.remnawave.defaultHwidDeviceLimit) > 0
      ) {
        patch.hwidDeviceLimit = Number(config.remnawave.defaultHwidDeviceLimit);
      }
      if (Object.keys(patch).length) {
        await rw.updateUser({
          uuid: users[0].uuid,
          patch,
        });
      }
    }
    const data = await loadMe(tid);
    return res.json({ ok: true, ...data });
  } catch (e) {
    return res.status(500).json({ error: e.message });
  }
});

app.post("/api/test/add-device-slot", authMiddleware, async (req, res) => {
  if (!config.testGrantEnabled) {
    return res.status(403).json({ error: "test_grant_disabled" });
  }
  const slots = Number(req.body?.slots || 1);
  if (!Number.isFinite(slots) || slots < 1) {
    return res.status(400).json({ error: "bad_slots" });
  }
  try {
    const tid = Number(req.tgSession.sub || req.tgSession.tg);
    const users = await rw.getUsersByTelegramId(tid);
    if (!users.length) {
      return res.status(404).json({ error: "subscription_not_found" });
    }
    const nextLimit = calcNewDeviceLimit(users[0]?.hwidDeviceLimit, slots);
    await rw.updateUser({
      uuid: users[0].uuid,
      patch: { hwidDeviceLimit: nextLimit },
    });
    const data = await loadMe(tid);
    return res.json({ ok: true, addedSlots: slots, hwidDeviceLimit: nextLimit, ...data });
  } catch (e) {
    return res.status(500).json({ error: e.message });
  }
});

const bot = new Bot(config.botToken);

bot.command("start", async (ctx) => {
  const kb = new InlineKeyboard().webApp("Подписка VPN", config.webAppUrl);
  await ctx.reply(
    "Открой мини-приложение: там статус подписки и подключение VPN.",
    { reply_markup: kb },
  );
});

if (config.publicBaseUrl) {
  app.use(whPath, webhookCallback(bot, "express", { secretToken: config.webhookSecret || undefined }));
}

app.use("/app", express.static(publicDir));
app.get(["/app", "/app/"], (_req, res) => {
  res.sendFile(path.join(publicDir, "index.html"));
});
app.get(/^\/app\/.*/, (_req, res) => {
  res.sendFile(path.join(publicDir, "index.html"));
});

app.listen(config.port, async () => {
  console.log(`http://127.0.0.1:${config.port}`);
  const base = config.publicBaseUrl?.replace(/\/$/, "");
  if (base) {
    const url = `${base}${whPath}`;
    const extra = config.webhookSecret ? { secret_token: config.webhookSecret } : {};
    await bot.api.setWebhook(url, extra);
    console.log("Telegram webhook ->", url);
  } else {
    console.log("PUBLIC_BASE_URL not set, using long polling");
    await bot.api.deleteWebhook({ drop_pending_updates: true });
    bot.start();
  }
});